userName: board-service
namingRoute: com.farmted.boardservice.config.CustomCamelCaseToSnakeAndLowerCaseStrategy
domain: ENC(WoHJzqygZ04vRr/NIpom6yznvPS5YL8Wnfcmffiq+4j5+KAYVa0IN0PwPannz6VOqhbkdPk0FY4nfsISkmmBjpuMFB6ncMdhcLpBSNDkLyVQdbX72e1Oir8TErUFVzws)