spring:
  application:
    name: product-service
  datasource:
    url: ENC(Vt6LVtSApI5e9FdZYSE49le+WELPV+3d5pasWd5B9RMBvAWmfiPg1e/kfFxpRbgl87haWz1T7KwQrSXssZegCmnFuQtjpxBulmLNKZXWx8Smt3LPU3p43gCWNybuTp+I615U+qw9FJY=)