spring:
  application:
    name: product-service
  datasource:
    url: ENC(Qc3UO8jC7l2t8vOdTYSYbqC5aNM7ju+QLY5NxKZtUWMrY5cUgpjImHxTrfe0SNFqiLcg/BnOlixLhbQuemLKsn/Hll2cEg37TbtH7ULfFU9y8fsrw1hpD1rQuqhE/MbrMuMyhCksfGA=)