# config.yml
spring:
  application:
    name: ${userName}
  datasource:
    url: ENC(0GVW2dA7FwZ/Uzdn9kZfvgwLtsTJzpZfGHB/jrciuXEOH5ME5cV7flFQkip5FyM3XeHuNArg9X336f0c/f8rftvZcCH4gJ3zL/GD48KqaS5EbkY3PBx8udlfoxEkjtDP)
    username: ENC(Wt6Ag+sWOVVT/vbTtFuctg==)
    password: ENC(O4LCGF7HLo4/rw1FGSJ9f9XkhrH/HRWl)
    driver-class-name: com.mysql.cj.jdbc.Driver
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# ${userName}과 ${dbUrl}은 개별 MS에서 사용하는 정보
# 드라이버는 암호화하니 아예 먹히지 않아서 그냥 씀