# config.yml
server:
  port: 0
spring:
  datasource:
    username: ENC(Wt6Ag+sWOVVT/vbTtFuctg==)
    password: ENC(O4LCGF7HLo4/rw1FGSJ9f9XkhrH/HRWl)
    driver-class-name: ENC(KbvVuKUI0/ongypma9NeAHH2HvqSBgtztbaTAM+2ZM9xAZvMwsDxKw==)
  #swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher