spring:
  application:
    name: member-service
  datasource:
    url: ENC(s8WpT240ynKaPaGFl3d6EjaNl5CqZ5/9oZTYcn3jh4/kVl+tg/AoJnqONruoZNzlLIlTRBusTy7LL1osvwOIoA7i5UQUGliDTVbFmrITY9MV6n8iabH3CsQ8XlrnKlHx)
spring.jpa.properties.hibernate.physical_naming_strategy: com.farmted.memberservice.config.CustomCamelCaseToSnakeAndLowerCaseStrategy